FROM tuxbox1/java8
#FROM openjdk:8-slim-bullseye

MAINTAINER tux-box <nathan.flow@gmail.com>

#persistant storage?
# Usage: VOLUME ["/dir_1", "/dir_2" ..]
#VOLUME ["/my_files"]

ENV MEM_MIN -Xms1024m
ENV MEM_MAX -Xmx2048m

ENV RUN_DIR   /starmade

RUN mkdir -p $RUN_DIR

#run commands directly rather than from file. this didn't seam to work adding files back to >
WORKDIR /starmade
COPY getFiles.sh /starmade/
COPY launchServer.sh /starmade/
#launch files on container start.
#WIP
ENTRYPOINT ["./starmade/getfiles.sh"]
ENTRYPOINT ["./starmade/launchServer.sh"]

ENTRYPOINT ["/starmade/getfiles.sh"]
ENTRYPOINT ["/starmade/launchServer.sh"]

ENTRYPOINT ["/bin/bash","./starmade/getfiles.sh"]
ENTRYPOINT ["/bin/bash","./starmade/launchServer.sh"]

ENTRYPOINT ["/bin/bash","/starmade/getfiles.sh"]
ENTRYPOINT ["/bin/bash","/starmade/launchServer.sh"]

ENTRYPOINT ./starmade/getfiles.sh
ENTRYPOINT ./starmade/launchServer.sh

ENTRYPOINT /starmade/getfiles.sh
ENTRYPOINT /starmade/launchServer.sh

ENTRYPOINT /bin/bash ./starmade/getfiles.sh
ENTRYPOINT /bin/bash ./starmade/launchServer.sh

ENTRYPOINT /bin/bash /starmade/getfiles.sh
ENTRYPOINT /bin/bash /starmade/launchServer.sh

EXPOSE 4242